### PR TITLE
added tutorials & resources

### PR DESCRIPTION
**Pull request by alpaca-power**
feel free to take a look to see if they're all right, thanks!

### CODE REVIEW

**Comment by kirang89** [comment]
Thanks for the numerous additions!  On another note, why exactly have you added 3 authors in place of 1 ?

**Comment by alpaca-power** [comment]
Hi Kiran,
Actually despite the readme I was under the impression that the "author" meant the authors of those tutorials. Did you mean for me to put my own name instead?

**Comment by kirang89** [comment]
Yea, it should just be your name. Do make that change and I'll be happy to merge this in :)

**Comment by alpaca-power** [comment]
done, thanks! :)

**Pull request merged**
